### ISSUE TITLE
Create a cid for exist files?

### ISSUE THREAD

**Issue by resrugam** [multiformats/cid#47]
Hi

Is there any way to create cidc for files??

**Comment by rvagg** [comment]
Use `ipfs add` to add to IPFS and return a CID, if in JS see this thread for some ideas for how to do it without needing to add a file: https://github.com/ipfs/js-ipfs/issues/1799, which also mentions https://github.com/alanshaw/ipfs-only-hash

In future, these kinds of queries are best asked on the IPFS forum @ https://discuss.ipfs.io/ or in the #ipfs:ipfs.io matrix chat room rather than here on GitHub.
